USE mysns;

ALTER TABLE user
ADD COLUMN bio VARCHAR(512);

ALTER TABLE feed
ADD COLUMN title VARCHAR(128);

CREATE TABLE IF NOT EXISTS reply(
    no INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    feed_no INT UNSIGNED,
    id VARCHAR(128),
    content VARCHAR(1024),
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

UPDATE feed
SET title = '제목 없음'
WHERE title IS NULL OR title = '';
